// Code generated by "stringer -type=Command"; DO NOT EDIT.

package slashcommand

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommandLabel-69]
	_ = x[CommandTrack-138]
}

const (
	_Command_name_0 = "CommandLabel"
	_Command_name_1 = "CommandTrack"
)

func (i Command) String() string {
	switch {
	case i == 69:
		return _Command_name_0
	case i == 138:
		return _Command_name_1
	default:
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
